### PR TITLE
Readme updates

### PR DESCRIPTION
**Pull request by aphelionz**
This PR updates the README content based on the latest Slack conversation and in preparation for a potential Ziggurat website.

### CODE REVIEW

**Comment by muzam1l** [comment]
Should we have all the details on the org readme page, as org readme's are commonly very short? To some, it means longer to scroll to see repos finally! Maybe a separate about page for now?

**Comment by aphelionz** [comment]
@muzam1l what if I just move the coverage table up after the short description and then logically follow it with Coverage Details?

**Comment by muzam1l** [comment]
> @muzam1l what if I just move the coverage table up after the short description and then logically follow it with Coverage Details?

That would be good, I was just concerned about the size of whole readme file, which should be concise and short!

**Comment by aphelionz** [comment]
I promise it at least won't get any longer :D

**Review by niklaslong — APPROVED** [review]

**Comment by aphelionz** [comment]
@muzam1l ok to merge?

**Review by muzam1l — APPROVED** [review]
🛳 it!

**Pull request merged**
